# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: [%pdf_directory_clubs%]
        public: true
        tags:
            - { name: twig.extension }